# Generated by Django 4.2.3 on 2023-07-04 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='MyLineItemId',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LineItems', to='tlkapi.orderinfo', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='log',
            name='LineItem',
            field=models.ForeignKey(db_column='MyLineItemId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Logs', to='tlkapi.lineitem'),
        ),
    ]
