# Generated by Django 4.2.3 on 2023-07-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0003_alter_lineitem_options_alter_lineitem_binnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LineItems', to='tlkapi.orderinfo', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='PrintedQuantity',
            field=models.IntegerField(db_column='PrintedQuantity', default=0),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='InsuranceCost',
            field=models.FloatField(db_column='InsuranceCost', default=0.0),
        ),
    ]
