# Generated by Django 4.2.3 on 2023-07-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0004_alter_lineitem_order_alter_lineitem_printedquantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Bin Number')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bins',
            },
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='BinNumber',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='BinNumber',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='Bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tlkapi.bin', verbose_name='Bin'),
        ),
    ]
