# Generated by Django 4.2.3 on 2023-07-08 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0005_bin_remove_lineitem_binnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bin',
            old_name='active',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='bin',
            old_name='number',
            new_name='Number',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='Bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='tlkapi.bin', verbose_name='Bin'),
        ),
    ]
