# Generated by Django 4.2.3 on 2023-07-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0006_rename_active_bin_active_rename_number_bin_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bin',
            options={'ordering': ['Number'], 'verbose_name': 'Bin', 'verbose_name_plural': 'Bins'},
        ),
        migrations.AlterField(
            model_name='bin',
            name='Number',
            field=models.IntegerField(unique=True, verbose_name='Bin Number'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='LineItemId',
            field=models.BigIntegerField(blank=True, db_column='LineItemId', null=True, unique=True),
        ),
    ]
