# Generated by Django 4.2.3 on 2023-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0007_alter_bin_options_alter_bin_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='Active',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='OrderNumber',
            field=models.CharField(default='dummy', max_length=50, verbose_name='OrderNumber'),
            preserve_default=False,
        ),
    ]
