# Generated by Django 4.2.3 on 2023-07-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0008_remove_orderinfo_active_orderinfo_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='AllItemsPrinted',
            field=models.BooleanField(default=False, verbose_name='All Printed'),
        ),
    ]
