# Generated by Django 4.2.3 on 2023-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0009_orderinfo_allitemsprinted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='Notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
