# Generated by Django 4.2.3 on 2023-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0010_bin_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='Customer',
            field=models.CharField(blank=True, db_column='Customer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='CustomerEmail',
            field=models.EmailField(blank=True, db_column='CustomerEmail', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='FinancialStatus',
            field=models.CharField(blank=True, db_column='FinancialStatus', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='FulfillmentStatus',
            field=models.CharField(blank=True, db_column='FulfillmentStatus', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='Name',
            field=models.CharField(blank=True, db_column='Name', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='OrderNumber',
            field=models.CharField(blank=True, db_column='OrderNumber', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='ProductImage',
            field=models.CharField(blank=True, db_column='ProductImage', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='Shipping',
            field=models.CharField(blank=True, db_column='Shipping', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='Sku',
            field=models.CharField(blank=True, db_column='Sku', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='Status',
            field=models.CharField(blank=True, db_column='Status', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='VariantTitle',
            field=models.CharField(blank=True, db_column='VariantTitle', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ChangeStatus',
            field=models.CharField(blank=True, db_column='ChangeStatus', max_length=50, null=True),
        ),
    ]
