# Generated by Django 4.2.3 on 2023-07-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0012_alter_orderinfo_trackingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='OrderId',
            field=models.BigIntegerField(blank=True, db_column='OrderId', null=True),
        ),
    ]
