# Generated by Django 4.2.3 on 2023-07-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0013_alter_orderinfo_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='Bin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Order', to='tlkapi.bin', verbose_name='Bin'),
        ),
    ]
