# Generated by Django 4.2.3 on 2023-07-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0015_alter_lineitem_status_alter_orderinfo_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='OrderNumber',
            field=models.CharField(default='-', max_length=50, verbose_name='OrderNumber'),
            preserve_default=False,
        ),
    ]
