# Generated by Django 4.2.3 on 2023-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0016_alter_orderinfo_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='OrderNumber',
            field=models.CharField(default='0', max_length=50, verbose_name='OrderNumber'),
        ),
    ]
