# Generated by Django 4.2.3 on 2023-07-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0018_alter_lineitem_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LineItems', to='tlkapi.orderinfo', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='OrderNumber',
            field=models.CharField(blank=True, db_column='OrderNumber', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='OrderNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OrderNumber'),
        ),
    ]
