# Generated by Django 4.2.3 on 2023-09-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlkapi', '0019_alter_lineitem_order_alter_lineitem_ordernumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Done', models.BooleanField(verbose_name='Done')),
                ('Timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('LineItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlkapi.lineitem', verbose_name='LineItem')),
            ],
            options={
                'verbose_name': 'Print Request',
                'verbose_name_plural': 'Print Requests',
            },
        ),
    ]
