# Generated by Django 4.2.3 on 2023-07-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('event', models.CharField(max_length=50, verbose_name='Event')),
                ('body', models.JSONField(blank=True, null=True, verbose_name='Body')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Headers')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed')),
            ],
            options={
                'verbose_name': 'hook',
                'verbose_name_plural': 'hooks',
            },
        ),
    ]
