# Generated by Django 4.2.3 on 2023-07-10 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyhook', '0002_alter_hook_event_alter_hook_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hook',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='hook',
            name='triggered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Triggered At'),
            preserve_default=False,
        ),
    ]
