# Generated by Django 4.2.3 on 2023-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopifyhook', '0003_remove_hook_timestamp_hook_triggered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='source',
            field=models.CharField(choices=[('Shopify', 0), ('ShipStation', 1)], default=0, max_length=20, verbose_name='Source'),
            preserve_default=False,
        ),
    ]
