# Generated by Django 4.2.3 on 2023-08-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50, verbose_name='Handle')),
                ('shopify_id', models.PositiveBigIntegerField(verbose_name='Product Id')),
                ('product_type', models.CharField(max_length=50, verbose_name='Product Type')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('shopify_id', models.PositiveBigIntegerField(verbose_name='Variant Id')),
                ('option1', models.CharField(max_length=50, verbose_name='Option 1')),
                ('option2', models.CharField(max_length=50, verbose_name='Option 2')),
                ('option3', models.CharField(max_length=50, verbose_name='Option 3')),
                ('sku', models.CharField(max_length=50, verbose_name='Sku')),
                ('new_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='New Sku')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'variant',
                'verbose_name_plural': 'variants',
            },
        ),
    ]
