# Generated by Django 4.2.3 on 2023-08-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='option1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Option 3'),
        ),
    ]
