# Generated by Django 4.2.3 on 2023-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sku'),
        ),
    ]
