# Generated by Django 4.2.3 on 2023-09-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_alter_variant_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(max_length=200, verbose_name='Handle'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='new_sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='New Sku'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Option 1'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Option 2'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='option3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Option 3'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sku'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
