# Generated by Django 4.2.3 on 2023-09-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_alter_product_handle_alter_variant_new_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sku_fixed',
            field=models.BooleanField(default=False, verbose_name='Sku Fixed'),
        ),
    ]
