# Generated by Django 4.2.3 on 2023-09-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_product_sku_fixed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Type')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type Code')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
    ]
